security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: 'argon2i'
        App\Entity\User\User:
            algorithm: 'argon2i'

    role_hierarchy:
        ROLE_USER: []
        ROLE_SONATA_ADMIN:
            - ROLE_USER
        ROLE_ADMIN:
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        App\Model\Security\UserProvider:
            id: App\Model\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: true

        admin:
            pattern: /admin(.*)
            context: app
            anonymous: true
            provider: App\Model\Security\UserProvider
            user_checker: App\Model\Security\UserCheckerAdmin
            form_login:
                login_path: /admin/login
                use_forward: false
                check_path: /admin/login/check
                failure_path: null
                default_target_path: sonata_admin_dashboard # default redirect to dashboard after login.
            logout:
                path: /admin/logout
                target: /admin/login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                path:     /admin
                always_remember_me: false # only when check the checkbox in login form.
                remember_me_parameter: _remember_me

        frontend:
            pattern: /(.*)
            anonymous: true

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_SONATA_ADMIN }
        - { path: ^/(.*), roles: IS_AUTHENTICATED_ANONYMOUSLY }
