sonata_admin:
    title: 'MapaÚtulků.cz'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    persist_filters:      true
    show_mosaic_button:   false
    global_search:
        empty_boxes: fade # show|fade|hide
    assets:
        remove_stylesheets:
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
        extra_stylesheets:
            - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-purple.min.css
#        extra_javascripts:
#            - assets/admin/js/Admin.custom.js
    options:
        html5_validate:       true
        # Auto order groups and admins by label or id
        sort_admins:          false
        confirm_exit:         true
        use_select2:          true
        use_icheck:           true
        use_bootlint:         false
        use_stickyforms:      true
        pager_links:          10
        form_type:            'standard'
        dropdown_number_groups_per_colums:  2
        title_mode:           'single_text' # One of "single_text"; "single_image"; "both"
        # Enable locking when editing an object, if the corresponding object manager supports it.
        lock_protection:      false
        # Enable automatic registration of annotations with JMSDiExtraBundle
        enable_jms_di_extra_autoregistration: true

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.timeline.block.timeline:
